- name: copy file
  copy: 
    src: "{{ item }}"
    dest: "/home/kai/opt/package/hadoop-2.7.2/etc/hadoop"
    owner: root
    group: root
    mode: 755
  with_items:
    - core-site.xml
    - hadoop-env.sh
    - hdfs-site.xml
    - mapred-env.sh
    - mapred-site.xml
    - yarn-env.sh
    - yarn-site.xml
    - slaves
    - white.hdfs.hosts

- name: install sshpass
  apt:
    name: sshpass
    state: present

- name: sync ssh-key
  script: ssh_copy_id.sh
  when:
    - ansible_nodename  == "node-3"
    
- name: stop timedatectl sync time
  shell: timedatectl set-ntp false

- name: stop ntp
  service:
    name: ntp
    state: stopped
  when: 
    - ansible_nodename  != "node-3"

- name: copy ntp.config
  copy: 
    src: ntp.conf
    dest: "/etc/ntp.conf"
    owner: root
    group: root
    mode: 755
  when:
    - ansible_nodename == "node-3"

- name: add crontab
  shell: echo '*/10 * * * * /usr/sbin/ntpdate node-3' >> /etc/crontab
  when: 
    - ansible_nodename != "node-3"

- name: restart crontab
  service: 
    name: cron
    state: restarted

- name: restart ntp
  service: 
    name: ntp
    state: restarted
  when: ansible_nodename == "node-3"
