- name: remove openjdk
  apt: 
    name: ["openjdk*"]
    state: absent

- name: install openjdk
  apt: 
    name: ['openjdk-11-jdk', 'openjdk-11-jdk-headless', 'wget', 'net-tools', 'ntp', 'ntpdate']
    state: present

- name: download hadoop-2.7.2
  shell: "wget http://archive.apache.org/dist/hadoop/core/hadoop-2.7.2/hadoop-2.7.2.tar.gz"

- name: create dir
  file: 
    path: "/home/kai/opt/package"
    state: "directory"

- name: tar hadoop-2.7.2
  shell: "tar zxf hadoop-2.7.2.tar.gz -C /home/kai/opt/package && mv /home/kai/opt/package/hadoop-2.7.2  /home/kai/opt/package/hadoop"

- name: set profile_env
  shell: echo '# hadoop\nexport HADOOP="~/opt/package/hadoop"\nexport PATH="$PATH:$HADOOP/bin:$HADOOP/sbin"' >> /home/kai/.bashrc
