- name: set env
  shell: sed -i {{ item }} /etc/ssh/sshd_config 
  with_items:
    - '/#UseLogin\ no/c\UseLogin\ yes'
    - '/#PermitRootLogin\ prohibit-password/c\PermitRootLogin\ yes'
  become: yes
  become_user: root
  become_method: sudo

- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
  become_user: root
  become_method: sudo